"use client";
import React, { createContext, useContext, useState } from "react";

// Create the context
const DataContext = createContext();

// Create a provider component
export const DataProvider = ({ children }) => {
  const universities = [
    "Shahjalal University of Science and Technology",
    "Bangladesh University of Engineering and Technology",
    "University of Dhaka",
    "Jahangirnagar University",
    "Islamic University of Technology",
    "BRAC University",
    "Pabna University of Science and Technology",
    "University of Rajshahi",
    "Military Institute of Science and Technology",
    "Bangladesh University of Professionals",
    "American International University-Bangladesh",
    "North South University",
    "East West University",
    "Daffodil International University",
    "University of Liberal Arts Bangladesh",
    "United International University",
    "Independent University, Bangladesh",
    "Southeast University",
    "Ahsanullah University of Science and Technology",
    "University of Asia Pacific",
  ];

  const departments = [
    "CSE",
    "SWE",
    "EEE",
    "CEE",
    "PHY",
    "MAT",
    "CHE",
    "BBA",
    "ECO",
    "LAW",
    "SOC",
    "ENG",
    "BIO",
    "ARC",
  ];

  const courses = [
    "Database",
    "Architecture",
    "AI",
    "ML",
    "SRE",
    "Datastructure",
    "OS",
    "OOP",
    "Economics",
    "Business Law",
    "Sociology",
    "Literature",
    "Biology",
    "Physics",
    "Chemistry",
  ];
  const appointments = [
    {
      name: "Ques1daD",
      owner: "md. rakibul kabir",
      year: 2024,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2dscs",
      owner: "siam ahmed",
      year: 2024,
      type: "Term Test",
      mark: "Mark",
    },
    {
      name: "Ques2SCSCZSC",
      owner: "arka das",
      year: 2024,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2xvzcvzSnfgjhdtyaesegsegsdgstgw4twetw",
      owner: "robin ahmed",
      year: 2023,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2xzvzxvz",
      owner: "mahfuzul hasan siam",
      year: 2023,
      type: "Term Test",
      mark: "Mark",
    },
    {
      name: "Ques2vxfgsdvx",
      owner: "rakib",
      year: 2023,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2cbxcbxcbxc",
      owner: "rakib",
      year: 2022,
      type: "Term Test",
      mark: "Mark",
    },
    {
      name: "Ques2dgsdgzdzdgzdgzdgzd",
      owner: "rakib",
      year: 2022,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2afzsdfzdfzdf",
      owner: "rakib",
      year: 2021,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2zdgzdgzdgvzd",
      owner: "rakib",
      year: 2021,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2zdvzxdvzxdcvzxcv",
      owner: "rakib",
      year: 2021,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2zvxdvbxfcbx",
      owner: "rakib",
      year: 2020,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2bxxfvxbvxcbvxc",
      owner: "rakib",
      year: 2020,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2xxfbcnbcgncg",
      owner: "rakib",
      year: 2020,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2019,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2018,
      type: "Semester",
      mark: "Mark",
    },
    {
      name: "Ques2",
      owner: "rakib",
      year: 2018,
      type: "Semester",
      mark: "Mark",
    },
  ];
  const doctorInfo = [
    {
      name: "Rakib",
      dept: "Cardiology",
      qualification: "MBBS",
      age: "34",
      gender: "Male",
      specialist: "Heart",
      number: "+880 1881665711",
    },
    {
      name: "Sadia",
      dept: "Neurology",
      qualification: "MD",
      age: "42",
      gender: "Female",
      specialist: "Brain",
      number: "+880 1881665722",
    },
    {
      name: "Arif",
      dept: "Orthopedics",
      qualification: "MBBS, MS",
      age: "38",
      gender: "Male",
      specialist: "Bones",
      number: "+880 1881665733",
    },
    {
      name: "Maya",
      dept: "Dermatology",
      qualification: "MBBS",
      age: "29",
      gender: "Female",
      specialist: "Skin",
      number: "+880 1881665744",
    },
    {
      name: "Nabil",
      dept: "Pediatrics",
      qualification: "MBBS, MD",
      age: "35",
      gender: "Male",
      specialist: "Child Care",
      number: "+880 1881665755",
    },
    {
      name: "Ritu",
      dept: "Gynecology",
      qualification: "MBBS, MD",
      age: "39",
      gender: "Female",
      specialist: "Pregnancy",
      number: "+880 1881665766",
    },
    {
      name: "Farhan",
      dept: "Urology",
      qualification: "MBBS, MS",
      age: "45",
      gender: "Male",
      specialist: "Kidney",
      number: "+880 1881665777",
    },
    {
      name: "Ayesha",
      dept: "Ophthalmology",
      qualification: "MBBS",
      age: "31",
      gender: "Female",
      specialist: "Eye",
      number: "+880 1881665788",
    },
    {
      name: "Tariq",
      dept: "Endocrinology",
      qualification: "MD",
      age: "47",
      gender: "Male",
      specialist: "Diabetes",
      number: "+880 1881665799",
    },
    {
      name: "Nasrin",
      dept: "Gastroenterology",
      qualification: "MBBS, MD",
      age: "37",
      gender: "Female",
      specialist: "Digestive System",
      number: "+880 1881665800",
    },
    {
      name: "Zahid",
      dept: "Psychiatry",
      qualification: "MBBS, MD",
      age: "50",
      gender: "Male",
      specialist: "Mental Health",
      number: "+880 1881665811",
    },
    {
      name: "Hina",
      dept: "Oncology",
      qualification: "MD",
      age: "41",
      gender: "Female",
      specialist: "Cancer",
      number: "+880 1881665822",
    },
    {
      name: "Rafiq",
      dept: "Pulmonology",
      qualification: "MBBS, MD",
      age: "33",
      gender: "Male",
      specialist: "Lungs",
      number: "+880 1881665833",
    },
    {
      name: "Rubina",
      dept: "Radiology",
      qualification: "MBBS",
      age: "44",
      gender: "Female",
      specialist: "Imaging",
      number: "+880 1881665844",
    },
    {
      name: "Samir",
      dept: "Nephrology",
      qualification: "MBBS, MD",
      age: "36",
      gender: "Male",
      specialist: "Kidney",
      number: "+880 1881665855",
    },
    {
      name: "Kamal",
      dept: "Hematology",
      qualification: "MBBS, MS",
      age: "43",
      gender: "Male",
      specialist: "Blood Disorders",
      number: "+880 1881665866",
    },
    {
      name: "Zara",
      dept: "Rheumatology",
      qualification: "MBBS",
      age: "28",
      gender: "Female",
      specialist: "Joints",
      number: "+880 1881665877",
    },
    {
      name: "Asif",
      dept: "Anesthesiology",
      qualification: "MD",
      age: "40",
      gender: "Male",
      specialist: "Anesthesia",
      number: "+880 1881665888",
    },
    {
      name: "Shireen",
      dept: "Otolaryngology",
      qualification: "MBBS",
      age: "48",
      gender: "Female",
      specialist: "Ear, Nose, Throat",
      number: "+880 1881665899",
    },
    {
      name: "Salman",
      dept: "Dentistry",
      qualification: "BDS",
      age: "32",
      gender: "Male",
      specialist: "Teeth",
      number: "+880 1881665900",
    },
  ];

  const myReports = [
    {
      testName: "Blood test",
      result: "Negative",
      amount: "300 tk",
      comment: "Take rest",
    },
    {
      testName: "X-ray",
      result: "Normal",
      amount: "500 tk",
      comment: "No issues found",
    },
    {
      testName: "Urine test",
      result: "Positive",
      amount: "200 tk",
      comment: "Drink more water",
    },
    {
      testName: "MRI scan",
      result: "Clear",
      amount: "2000 tk",
      comment: "Follow up needed",
    },
    {
      testName: "CT scan",
      result: "Abnormal",
      amount: "1500 tk",
      comment: "Consult specialist",
    },
    {
      testName: "ECG",
      result: "Normal",
      amount: "800 tk",
      comment: "Heart function normal",
    },
    {
      testName: "Cholesterol test",
      result: "High",
      amount: "400 tk",
      comment: "Control diet",
    },
    {
      testName: "Liver function test",
      result: "Normal",
      amount: "600 tk",
      comment: "No abnormalities",
    },
    {
      testName: "Thyroid test",
      result: "Low",
      amount: "450 tk",
      comment: "Medication prescribed",
    },
    {
      testName: "Blood sugar test",
      result: "High",
      amount: "300 tk",
      comment: "Monitor diet and sugar intake",
    },
    {
      testName: "Allergy test",
      result: "Positive",
      amount: "700 tk",
      comment: "Avoid allergens",
    },
    {
      testName: "Vitamin D test",
      result: "Deficient",
      amount: "550 tk",
      comment: "Take supplements",
    },
    {
      testName: "Kidney function test",
      result: "Normal",
      amount: "650 tk",
      comment: "Kidney is functioning well",
    },
    {
      testName: "Hemoglobin test",
      result: "Low",
      amount: "350 tk",
      comment: "Take iron supplements",
    },
    {
      testName: "Eye test",
      result: "20/20",
      amount: "250 tk",
      comment: "No vision issues",
    },
    {
      testName: "Heart ultrasound",
      result: "Healthy",
      amount: "1800 tk",
      comment: "No abnormalities detected",
    },
    {
      testName: "Bone density test",
      result: "Low",
      amount: "900 tk",
      comment: "Calcium supplements recommended",
    },
    {
      testName: "Lung function test",
      result: "Normal",
      amount: "400 tk",
      comment: "No issues with lung capacity",
    },
    {
      testName: "Stool test",
      result: "Negative",
      amount: "350 tk",
      comment: "No signs of infection",
    },
    {
      testName: "HIV test",
      result: "Negative",
      amount: "1000 tk",
      comment: "No further tests required",
    },
  ];
  const cabinRoomList = [
    {
      name: "cabin-1",
      roomNumber: "201-B",
      assignedNurse: "Mrs. Tanjid Khan",
      supervisingDoctor: "Dr. Younius Khan",
      caseSummary: "Need 24 hours to observe",
      bill: "3000 tk",
    },
    {
      name: "cabin-2",
      roomNumber: "202-A",
      assignedNurse: "Mr. Aminul Islam",
      supervisingDoctor: "Dr. Rakib Hasan",
      caseSummary: "Post-surgery recovery",
      bill: "4000 tk",
    },
    {
      name: "cabin-3",
      roomNumber: "203-C",
      assignedNurse: "Mrs. Salma Begum",
      supervisingDoctor: "Dr. Maria Haque",
      caseSummary: "Observation for 48 hours",
      bill: "3500 tk",
    },
    {
      name: "cabin-4",
      roomNumber: "204-D",
      assignedNurse: "Ms. Faria Khan",
      supervisingDoctor: "Dr. Faruk Ahmed",
      caseSummary: "Routine checkup",
      bill: "3200 tk",
    },
    {
      name: "cabin-5",
      roomNumber: "205-B",
      assignedNurse: "Mr. Shahidul Islam",
      supervisingDoctor: "Dr. Sarah Rahman",
      caseSummary: "Patient recovering well",
      bill: "5000 tk",
    },
    {
      name: "cabin-6",
      roomNumber: "206-A",
      assignedNurse: "Mrs. Anika Zaman",
      supervisingDoctor: "Dr. Karim Ullah",
      caseSummary: "Undergoing treatment for infection",
      bill: "4200 tk",
    },
    {
      name: "cabin-7",
      roomNumber: "207-C",
      assignedNurse: "Mr. Sadiq Rahman",
      supervisingDoctor: "Dr. Fahim Ahsan",
      caseSummary: "Need 48 hours for further tests",
      bill: "3800 tk",
    },
    {
      name: "cabin-8",
      roomNumber: "208-B",
      assignedNurse: "Ms. Laila Chowdhury",
      supervisingDoctor: "Dr. Kamal Uddin",
      caseSummary: "Post-accident care",
      bill: "6000 tk",
    },
    {
      name: "cabin-9",
      roomNumber: "209-A",
      assignedNurse: "Mrs. Tania Noor",
      supervisingDoctor: "Dr. Shahed Malik",
      caseSummary: "Patient stable, needs observation",
      bill: "3400 tk",
    },
    {
      name: "cabin-10",
      roomNumber: "210-C",
      assignedNurse: "Mr. Omar Farooq",
      supervisingDoctor: "Dr. Salim Sheikh",
      caseSummary: "Critical condition, constant monitoring",
      bill: "8000 tk",
    },
    {
      name: "cabin-11",
      roomNumber: "211-B",
      assignedNurse: "Mrs. Nazia Rahman",
      supervisingDoctor: "Dr. Jamil Haque",
      caseSummary: "Observation for 72 hours",
      bill: "4500 tk",
    },
    {
      name: "cabin-12",
      roomNumber: "212-A",
      assignedNurse: "Ms. Rima Sultana",
      supervisingDoctor: "Dr. Afzal Hossain",
      caseSummary: "Awaiting test results",
      bill: "3600 tk",
    },
    {
      name: "cabin-13",
      roomNumber: "213-D",
      assignedNurse: "Mr. Iqbal Khan",
      supervisingDoctor: "Dr. Nasrin Jahan",
      caseSummary: "Undergoing treatment for high fever",
      bill: "3300 tk",
    },
    {
      name: "cabin-14",
      roomNumber: "214-B",
      assignedNurse: "Mrs. Sumaiya Khatun",
      supervisingDoctor: "Dr. Imran Siddique",
      caseSummary: "Post-op recovery, 48-hour observation",
      bill: "5200 tk",
    },
    {
      name: "cabin-15",
      roomNumber: "215-A",
      assignedNurse: "Mr. Rahat Choudhury",
      supervisingDoctor: "Dr. Mahbub Alam",
      caseSummary: "Stable condition, under treatment",
      bill: "3100 tk",
    },
    {
      name: "cabin-16",
      roomNumber: "216-C",
      assignedNurse: "Ms. Noor Jahan",
      supervisingDoctor: "Dr. Tahmina Rahman",
      caseSummary: "Routine post-surgery check",
      bill: "3700 tk",
    },
    {
      name: "cabin-17",
      roomNumber: "217-B",
      assignedNurse: "Mrs. Lubna Chowdhury",
      supervisingDoctor: "Dr. Ehsan Ahmed",
      caseSummary: "Under treatment for viral infection",
      bill: "4300 tk",
    },
    {
      name: "cabin-18",
      roomNumber: "218-A",
      assignedNurse: "Mr. Jamal Khan",
      supervisingDoctor: "Dr. Kazi Rahim",
      caseSummary: "Patient needs extended care",
      bill: "5400 tk",
    },
    {
      name: "cabin-19",
      roomNumber: "219-D",
      assignedNurse: "Ms. Arifa Khan",
      supervisingDoctor: "Dr. Shakib Hasan",
      caseSummary: "Scheduled for surgery",
      bill: "7500 tk",
    },
    {
      name: "cabin-20",
      roomNumber: "220-B",
      assignedNurse: "Mr. Hasan Hossain",
      supervisingDoctor: "Dr. Tasnim Rahman",
      caseSummary: "Under observation for 24 hours",
      bill: "4100 tk",
    },
  ];
  
  const wardRoomList = [
    {
      name: "ward-1",
      roomNumber: "201-B",
      assignedNurse: "Mrs. Tanjid Khan",
      supervisingDoctor: "Dr. Younius Khan",
      caseSummary: "Need 24 hours to observe",
      bill: "3000 tk",
    },
    {
      name: "ward-2",
      roomNumber: "202-A",
      assignedNurse: "Mr. Aminul Islam",
      supervisingDoctor: "Dr. Rakib Hasan",
      caseSummary: "Post-surgery recovery",
      bill: "4000 tk",
    },
    {
      name: "ward-3",
      roomNumber: "203-C",
      assignedNurse: "Mrs. Salma Begum",
      supervisingDoctor: "Dr. Maria Haque",
      caseSummary: "Observation for 48 hours",
      bill: "3500 tk",
    },
    {
      name: "ward-4",
      roomNumber: "204-D",
      assignedNurse: "Ms. Faria Khan",
      supervisingDoctor: "Dr. Faruk Ahmed",
      caseSummary: "Routine checkup",
      bill: "3200 tk",
    },
    {
      name: "ward-5",
      roomNumber: "205-B",
      assignedNurse: "Mr. Shahidul Islam",
      supervisingDoctor: "Dr. Sarah Rahman",
      caseSummary: "Patient recovering well",
      bill: "5000 tk",
    },
    {
      name: "ward-6",
      roomNumber: "206-A",
      assignedNurse: "Mrs. Anika Zaman",
      supervisingDoctor: "Dr. Karim Ullah",
      caseSummary: "Undergoing treatment for infection",
      bill: "4200 tk",
    },
    {
      name: "ward-7",
      roomNumber: "207-C",
      assignedNurse: "Mr. Sadiq Rahman",
      supervisingDoctor: "Dr. Fahim Ahsan",
      caseSummary: "Need 48 hours for further tests",
      bill: "3800 tk",
    },
    {
      name: "ward-8",
      roomNumber: "208-B",
      assignedNurse: "Ms. Laila Chowdhury",
      supervisingDoctor: "Dr. Kamal Uddin",
      caseSummary: "Post-accident care",
      bill: "6000 tk",
    },
    {
      name: "ward-9",
      roomNumber: "209-A",
      assignedNurse: "Mrs. Tania Noor",
      supervisingDoctor: "Dr. Shahed Malik",
      caseSummary: "Patient stable, needs observation",
      bill: "3400 tk",
    },
    {
      name: "ward-10",
      roomNumber: "210-C",
      assignedNurse: "Mr. Omar Farooq",
      supervisingDoctor: "Dr. Salim Sheikh",
      caseSummary: "Critical condition, constant monitoring",
      bill: "8000 tk",
    },
    {
      name: "ward-11",
      roomNumber: "211-B",
      assignedNurse: "Mrs. Nazia Rahman",
      supervisingDoctor: "Dr. Jamil Haque",
      caseSummary: "Observation for 72 hours",
      bill: "4500 tk",
    },
    {
      name: "ward-12",
      roomNumber: "212-A",
      assignedNurse: "Ms. Rima Sultana",
      supervisingDoctor: "Dr. Afzal Hossain",
      caseSummary: "Awaiting test results",
      bill: "3600 tk",
    },
    {
      name: "ward-13",
      roomNumber: "213-D",
      assignedNurse: "Mr. Iqbal Khan",
      supervisingDoctor: "Dr. Nasrin Jahan",
      caseSummary: "Undergoing treatment for high fever",
      bill: "3300 tk",
    },
    {
      name: "ward-14",
      roomNumber: "214-B",
      assignedNurse: "Mrs. Sumaiya Khatun",
      supervisingDoctor: "Dr. Imran Siddique",
      caseSummary: "Post-op recovery, 48-hour observation",
      bill: "5200 tk",
    },
    {
      name: "ward-15",
      roomNumber: "215-A",
      assignedNurse: "Mr. Rahat Choudhury",
      supervisingDoctor: "Dr. Mahbub Alam",
      caseSummary: "Stable condition, under treatment",
      bill: "3100 tk",
    },
    {
      name: "ward-16",
      roomNumber: "216-C",
      assignedNurse: "Ms. Noor Jahan",
      supervisingDoctor: "Dr. Tahmina Rahman",
      caseSummary: "Routine post-surgery check",
      bill: "3700 tk",
    },
    {
      name: "ward-17",
      roomNumber: "217-B",
      assignedNurse: "Mrs. Lubna Chowdhury",
      supervisingDoctor: "Dr. Ehsan Ahmed",
      caseSummary: "Under treatment for viral infection",
      bill: "4300 tk",
    },
    {
      name: "ward-18",
      roomNumber: "218-A",
      assignedNurse: "Mr. Jamal Khan",
      supervisingDoctor: "Dr. Kazi Rahim",
      caseSummary: "Patient needs extended care",
      bill: "5400 tk",
    },
    {
      name: "ward-19",
      roomNumber: "219-D",
      assignedNurse: "Ms. Arifa Khan",
      supervisingDoctor: "Dr. Shakib Hasan",
      caseSummary: "Scheduled for surgery",
      bill: "7500 tk",
    },
    {
      name: "ward-20",
      roomNumber: "220-B",
      assignedNurse: "Mr. Hasan Hossain",
      supervisingDoctor: "Dr. Tasnim Rahman",
      caseSummary: "Under observation for 24 hours",
      bill: "4100 tk",
    },
  ];
  const availableTest = [
    {
      name: "Blood test",
      amount: "300 tk",
      time: "07:30 PM",
    },
    {
      name: "X-ray",
      amount: "500 tk",
      time: "08:00 AM",
    },
    {
      name: "MRI Scan",
      amount: "3000 tk",
      time: "10:30 AM",
    },
    {
      name: "CT Scan",
      amount: "4000 tk",
      time: "11:00 AM",
    },
    {
      name: "Urine test",
      amount: "200 tk",
      time: "09:00 AM",
    },
    {
      name: "ECG",
      amount: "1500 tk",
      time: "02:00 PM",
    },
    {
      name: "Cholesterol test",
      amount: "600 tk",
      time: "03:00 PM",
    },
    {
      name: "Blood Sugar test",
      amount: "350 tk",
      time: "08:45 AM",
    },
    {
      name: "Liver Function test",
      amount: "1200 tk",
      time: "12:00 PM",
    },
    {
      name: "Kidney Function test",
      amount: "1000 tk",
      time: "01:30 PM",
    },
    {
      name: "HIV test",
      amount: "1800 tk",
      time: "04:00 PM",
    },
    {
      name: "Thyroid Function test",
      amount: "900 tk",
      time: "10:00 AM",
    },
    {
      name: "Pregnancy test",
      amount: "300 tk",
      time: "09:15 AM",
    },
    {
      name: "Vitamin D test",
      amount: "700 tk",
      time: "01:00 PM",
    },
    {
      name: "Complete Blood Count",
      amount: "500 tk",
      time: "02:45 PM",
    },
    {
      name: "Urine Culture test",
      amount: "600 tk",
      time: "03:30 PM",
    },
    {
      name: "Lipid Profile test",
      amount: "1200 tk",
      time: "11:30 AM",
    },
    {
      name: "Hemoglobin test",
      amount: "300 tk",
      time: "07:00 PM",
    },
    {
      name: "Allergy test",
      amount: "2500 tk",
      time: "05:00 PM",
    },
    {
      name: "Bone Density test",
      amount: "2000 tk",
      time: "06:00 PM",
    },
  ];
  

  return (
    <DataContext.Provider
      value={{
        appointments,
        doctorInfo,
        myReports,
        cabinRoomList,
        wardRoomList,
        availableTest
      }}
    >
      {children}
    </DataContext.Provider>
  );
};

// Custom hook for consuming the data context
export const useDataContext = () => {
  return useContext(DataContext);
};
